# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: notifications/hero.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("notifications/hero.proto", :syntax => :proto3) do
    add_message "hero.HeroById" do
      optional :id, :int32, 1
    end
    add_message "hero.SampleMessage" do
      oneof :test_oneof do
        optional :name, :string, 4
        optional :sub_message, :message, 9, "hero.Hero"
      end
    end
    add_message "hero.Hero" do
      optional :id, :int32, 1
      optional :name, :string, 2
      optional :corpus, :enum, 4, "hero.Corpus"
      repeated :results, :enum, 5, "hero.Corpus"
      repeated :details, :string, 6
      map :projects, :string, :message, 7, "hero.Hero"
    end
    add_enum "hero.Corpus" do
      value :CORPUS_UNSPECIFIED, 0
      value :CORPUS_UNIVERSAL, 1
      value :CORPUS_WEB, 2
    end
  end
end

module Hero
  HeroById = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hero.HeroById").msgclass
  SampleMessage = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hero.SampleMessage").msgclass
  Hero = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hero.Hero").msgclass
  Corpus = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hero.Corpus").enummodule
end
